CONTRIBUTING.md
=> small correction in contributing md

classifiers/__init__.py, classifiers/premiums/gpt3_classifier/README.md, classifiers/premiums/gpt3_classifier/__init__.py, classifiers/premiums/gpt3_classifier/code_snippet.md, classifiers/premiums/gpt3_classifier/config.py, requirements.txt, util/configs.py
=> Added a gpt3 classifier

generators/__init__.py, generators/premiums/ibm_translator/README.md, generators/premiums/ibm_translator/__init__.py, generators/premiums/ibm_translator/code_snippet.md, generators/premiums/ibm_translator/config.py
=> Ibm translator

classifiers/active_learners/grid_search/README.md, classifiers/active_learners/grid_search/__init__.py, classifiers/active_learners/grid_search/code_snippet.md, classifiers/active_learners/grid_search/config.py
=> Grid search

generators/__init__.py, generators/premiums/gpt3_tldr_summarization/README.md, generators/premiums/gpt3_tldr_summarization/__init__.py, generators/premiums/gpt3_tldr_summarization/code_snippet.md, generators/premiums/gpt3_tldr_summarization/config.py
Implements #195 
Works well with the api key :)
=> Gpt3 text summariser

generators/__init__.py, generators/premiums/bing_news_search/README.md, generators/premiums/bing_news_search/__init__.py, generators/premiums/bing_news_search/code_snippet.md, generators/premiums/bing_news_search/config.py
=> Bing news search

generators/__init__.py, generators/premiums/gpt3_restaurant_review/README.md, generators/premiums/gpt3_restaurant_review/__init__.py, generators/premiums/gpt3_restaurant_review/code_snippet.md, generators/premiums/gpt3_restaurant_review/config.py
=> GPT3 restaurant review generator

extractors/__init__.py, extractors/python_functions/verb_phrase_extraction/README.md, extractors/python_functions/verb_phrase_extraction/__init__.py, extractors/python_functions/verb_phrase_extraction/code_snippet.md, extractors/python_functions/verb_phrase_extraction/config.py, requirements.txt
Implements #238 
Tested on local machine.
=> Implement the verb_phrase_extractor

generators/__init__.py, generators/python_functions/most_frequent_words/README.md, generators/python_functions/most_frequent_words/__init__.py, generators/python_functions/most_frequent_words/code_snippet.md, generators/python_functions/most_frequent_words/config.py
=> Implement module to generate the most frequent words from a text

classifiers/active_learners/decision_tree/code_snippet.md, classifiers/active_learners/grid_search/code_snippet.md, classifiers/active_learners/logistic_regression/code_snippet.md, classifiers/active_learners/random_forest/code_snippet.md, classifiers/active_learners/random_search/code_snippet.md, extractors/active_learners/crf_tagger/code_snippet.md
Changes:
- call abstract method `predict_prob` -> `predict_proba`
- `self.model.predict` -> `self.model.predict_proba`
- added the number of iterations as a user defined variable `YOUR_ITERATIONS`
=> fix the active learning modules in context to refinery workflow

classifiers/python_functions/vader_sentiment/code_snippet.md
=> Updated import statement for vader sentiment in code snippet 

generators/__init__.py, generators/python_functions/manhattan_distance/README.md, generators/python_functions/manhattan_distance/__init__.py, generators/python_functions/manhattan_distance/code_snippet.md, generators/python_functions/manhattan_distance/config.py
=> Added manhattan distance metric brick

classifiers/python_functions/lookup_list/__init__.py, classifiers/python_functions/lookup_list/code_snippet.md, classifiers/python_functions/spelling_check/code_snippet.md, classifiers/python_functions/textblob_sentiment/code_snippet.md, classifiers/python_functions/vader_sentiment/code_snippet.md, extractors/python_functions/gazetteer_extraction/code_snippet.md, extractors/python_functions/keyword_extraction/code_snippet.md, extractors/python_functions/window_search_extraction/code_snippet.md, extractors/python_functions/zipcode_extraction/code_snippet.md
=> Added typing imports and fixed faulty return statements in code_snippets

extractors/dates_and_times/date_extraction/code_snippet_refinery.md, extractors/words/difficult_words_extraction/code_snippet_refinery.md, extractors/words/difficult_words_extraction/config.py, extractors/words/goodbye_extraction/code_snippet_refinery.md, extractors/words/smalltalk_extraction/code_snippet_refinery.md, extractors/words/synonym_extraction/code_snippet_refinery.md
=> Adds changes from finiding session

generators/paths/domain_parser/__init__.py
=> Added missing DocString for domain parser

classifiers/dates_and_times/workday_classifier/code_snippet_refinery.md
=> Workday classifier attribute fix

classifiers/__init__.py, classifiers/llm/bert_sentiment_german/README.md, classifiers/llm/bert_sentiment_german/__init__.py, classifiers/llm/bert_sentiment_german/code_snippet_common.md, classifiers/llm/bert_sentiment_german/code_snippet_refinery.md, classifiers/llm/bert_sentiment_german/config.py
=> Bert sentiment german

classifiers/text_analysis/language_detection/__init__.py, classifiers/text_analysis/language_detection/code_snippet_common.md, classifiers/text_analysis/language_detection/code_snippet_refinery.md
Returns unknown if a string is empty.
=> Added small failsave clause to language detection

classifiers/reference_complexity/chunked_sentence_complexity/config.py, classifiers/reference_complexity/tiktoken_length_classifier/config.py
Added as a group to:
- chunked sentence complexity
- tiktoken length classifier
=> Adds question complexity as group

classifiers/__init__.py, extractors/__init__.py, generators/__init__.py
Note that this is not a feature change / extension but a change for the global endpoint definition. 
Best to test locally with multiple simultanious request.
might need some further changes for the fast api configuration (e.g. maybe more workers)
=> Removes async keyword
